In [103]:
import sqlite3, pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

DB = '../pipeline/amazon_tracker.db'
conn = sqlite3.connect(DB)
print('Connected to DB')

Connected to DB

## Today's Sellers — All ASINs

In [110]:
test1 = pd.read_sql("""
    SELECT *
    FROM dim_product 
""", conn)
test1

           asin parent_asin                                              title                          brand variation_size variation_color
0    B0F8QT93ZK  B0F91T6F6C                                                                                            Large            Blue
1    B0FLVWDS32  B0FLVWDS32                                                                                             None            None
2    B0FVTSXT96  B0FVTSBKZP                                                                                            Small          Purple
3    B0FVTT89X4  B0FVTSBKZP                                                                                           Medium          Purple
4    B0FVTRNBPN  B0FVTSBKZP                                                                                            Large          Purple
..          ...         ...                                                ...                            ...            ...             ...
247  B0GS3M645K  B0GS3H5K4G  Weatherproof Vintage Men's Water Resistant Act...  Original Weatherproof Vintage      36W x 29L             Tan
248  B0GS3HV8VN  B0GS3H5K4G  Weatherproof Vintage Men's Water Resistant Act...  Original Weatherproof Vintage      36W x 30L             Tan
249  B0GS3N7PGF  B0GS3H5K4G  Weatherproof Vintage Men's Water Resistant Act...  Original Weatherproof Vintage      36W x 32L             Tan
250  B0GS3GVJ3R  B0GS3H5K4G  Weatherproof Vintage Men's Water Resistant Act...  Original Weatherproof Vintage      36W x 34L             Tan
251  B0GS3CYYX5  B0GS3H5K4G  Weatherproof Vintage Men's Water Resistant Act...  Original Weatherproof Vintage      38W x 29L             Tan

[252 rows x 6 columns]

In [84]:
test2 = pd.read_sql("""
    SELECT *
    FROM fct_asin_daily 
""", conn)
test2

,snapshot_date,asin,bsr_rank,bsr_category,sellers,total_sellers,fba_sellers,fbm_sellers,min_price,max_price,avg_price_weighted,total_inventory,units_sold,fba_units_sold,fbm_units_sold
0,2026-05-17,B0F8QT93ZK,80046,"Clothing, Shoes & Jewelry","[{""name"": ""SaMe Market"", ""fulfillment"": ""FBA"",...",6,4,2,32.99,36.99,35.483377,77,None,None,None
1,2026-05-17,B0FLVWDS32,1669467,"Clothing, Shoes & Jewelry","[{""name"": ""OMNI LINENS"", ""fulfillment"": ""FBM"",...",1,0,1,39.95,39.95,39.950000,10,None,None,None
2,2026-05-17,B0FVTSXT96,521386,"Clothing, Shoes & Jewelry","[{""name"": ""Discount Scrubs and Fashion"", ""fulf...",9,3,6,16.35,25.00,23.337391,23,None,None,None
3,2026-05-17,B0FVTT89X4,521386,"Clothing, Shoes & Jewelry","[{""name"": ""Discount Scrubs and Fashion"", ""fulf...",8,1,7,15.40,21.88,19.497143,14,None,None,None
4,2026-05-17,B0FVTRNBPN,521386,"Clothing, Shoes & Jewelry","[{""name"": ""Saint Rebekah For Trading"", ""fulfil...",3,0,3,19.95,20.00,19.966667,3,None,None,None
5,2026-05-17,B0FVTVCVS8,521386,"Clothing, Shoes & Jewelry","[{""name"": ""Eclectic Media and Goods"", ""fulfill...",6,1,5,11.99,23.16,21.291538,13,None,None,None
6,2026-05-17,B0FVTT3XX1,521386,"Clothing, Shoes & Jewelry","[{""name"": ""unique-treasure-finds"", ""fulfillmen...",11,3,8,8.95,19.10,13.709014,142,None,None,None
7,2026-05-17,B0FVTSHWKP,521035,"Clothing, Shoes & Jewelry","[{""name"": ""Martin's Merchandise"", ""fulfillment...",11,4,7,15.88,25.99,21.310000,65,None,None,None
8,2026-05-17,B0FVTTSRJM,521386,"Clothing, Shoes & Jewelry","[{""name"": ""K & X"", ""fulfillment"": ""FBA"", ""pric...",10,5,5,18.68,28.99,25.689123,57,None,None,None
9,2026-05-17,B0FVTTG1SR,521386,"Clothing, Shoes & Jewelry","[{""name"": ""Bobbos 2003"", ""fulfillment"": ""FBM"",...",10,3,7,14.83,34.99,24.790000,28,None,None,None
10,2026-05-17,B0FVTS2NJ5,521386,"Clothing, Shoes & Jewelry","[{""name"": ""unique-treasure-finds"", ""fulfillmen...",11,3,8,8.95,19.10,13.709014,142,None,None,None
11,2026-05-17,B0FVTS122P,521386,"Clothing, Shoes & Jewelry","[{""name"": ""unique-treasure-finds"", ""fulfillmen...",11,3,8,8.95,19.10,13.709014,142,None,None,None
12,2026-05-17,B0FVTP51M4,521386,"Clothing, Shoes & Jewelry","[{""name"": ""unique-treasure-finds"", ""fulfillmen...",11,3,8,8.95,19.10,13.709014,142,None,None,None
13,2026-05-17,B0FVTSXG1T,521386,"Clothing, Shoes & Jewelry","[{""name"": ""unique-treasure-finds"", ""fulfillmen...",11,3,8,8.95,18.99,13.506901,142,None,None,None
14,2026-05-17,B0FFN7LWKK,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",4,1,3,32.95,43.99,40.066667,6,None,None,None
15,2026-05-17,B0FFNBSF1Y,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",5,1,4,32.95,54.99,43.774444,18,None,None,None
16,2026-05-17,B0FFNDDM8S,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",5,1,4,32.95,54.99,45.603226,31,None,None,None
17,2026-05-17,B0FFN7YBL1,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",5,1,4,32.95,54.99,43.759615,26,None,None,None
18,2026-05-17,B0FFNB1PC5,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",6,2,4,32.95,52.99,44.233750,16,None,None,None
19,2026-05-17,B0FFN122S5,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""LION-go"", ""fulfillment"": ""FBA"", ""pr...",5,2,3,42.97,54.99,43.698889,45,None,None,None
20,2026-05-17,B0FFN8YDNQ,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",5,2,3,32.95,45.69,42.070000,19,None,None,None
21,2026-05-17,B0FFN89JXC,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",4,1,3,32.95,54.99,43.387647,17,None,None,None
22,2026-05-17,B0FFN8GNT3,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",5,2,3,32.95,54.99,42.972500,24,None,None,None
23,2026-05-17,B0FFN4TYVV,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",6,2,4,34.95,54.89,45.415926,27,None,None,None
24,2026-05-17,B0FFN8TTV7,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""ONDIBS"", ""fulfillment"": ""FBM"", ""pri...",5,2,3,34.95,54.99,47.650000,18,None,None,None
25,2026-05-17,B0FFN883NT,2088845,"Clothing, Shoes & Jewelry","[{""name"": ""SaMe Market"", ""fulfillment"": ""FBM"",...",3,1,2,42.99,47.99,43.293333,30,None,None,None

In [56]:
test3 = pd.read_sql("""
    SELECT *
    FROM fact_bsr_snapshot 
""", conn)
test3

   bsr_id snapshot_date  snapshot_hour  product_id  bsr_rank               bsr_category          ingested_at
0       1    2026-05-17              0           1    295015  Clothing, Shoes & Jewelry  2026-05-17 16:09:03
1       2    2026-05-17              0           2     80046  Clothing, Shoes & Jewelry  2026-05-17 16:10:01
2       3    2026-05-17              0           3    471556  Clothing, Shoes & Jewelry  2026-05-17 16:11:04

In [57]:
test4 = pd.read_sql("""
    SELECT *
    FROM fact_daily_units_sold 
""", conn)
test4

Empty DataFrame
Columns: [record_id, calc_date, product_id, seller_id, fulfillment, inv_yesterday, inv_today, units_sold, oos_sold, is_new_seller]
Index: []

In [58]:
test5 = pd.read_sql("""
    SELECT *
    FROM fact_seller_snapshot 
""", conn)
test5

    snapshot_id snapshot_date  snapshot_hour  product_id  seller_id  price  shipping_cost  total_price  inventory  is_buy_box_winner raw_json          ingested_at
0             2    2026-05-17              0           1          2  42.00            0.0        42.00        2.0                  0     None  2026-05-17 16:09:03
1             3    2026-05-17              0           1          3  45.95            0.0        45.95        2.0                  0     None  2026-05-17 16:09:03
2             4    2026-05-17              0           1          4  49.90            0.0        49.90        2.0                  0     None  2026-05-17 16:09:03
3             5    2026-05-17              0           1          1  37.98            0.0        37.98        NaN                  1     None  2026-05-17 16:09:03
4             6    2026-05-17              0           2          6  32.99            0.0        32.99       11.0                  0     None  2026-05-17 16:10:01
5             7    2026-05-17              0           2          7  32.99            0.0        32.99        1.0                  0     None  2026-05-17 16:10:01
6             8    2026-05-17              0           2          8  34.98            0.0        34.98        1.0                  0     None  2026-05-17 16:10:01
7             9    2026-05-17              0           2          9  34.99            0.0        34.99       30.0                  0     None  2026-05-17 16:10:01
8            10    2026-05-17              0           2         10  34.99            0.0        34.99        5.0                  0     None  2026-05-17 16:10:01
9            12    2026-05-17              0           2         11  42.99            0.0        42.99        5.0                  0     None  2026-05-17 16:10:01
10           14    2026-05-17              0           3         14  24.95            0.0        24.95        1.0                  0     None  2026-05-17 16:11:04
11           15    2026-05-17              0           3          1  24.95            0.0        24.95        NaN                  1     None  2026-05-17 16:11:04

In [59]:
test6 = pd.read_sql("""
    SELECT *
    FROM v_daily_sales_summary 
""", conn)
test6

Empty DataFrame
Columns: [calc_date, asin, title, total_units_sold, fba_sold, fbm_sold, active_sellers]
Index: []

## Units Sold Per Seller (after 2nd day of data)

In [ ]:
sales = pd.read_sql("""
    SELECT u.calc_date, p.asin, s.seller_name, s.fulfillment,
           u.inv_yesterday, u.inv_today, u.units_sold, u.oos_sold
    FROM fact_daily_units_sold u
    JOIN dim_product p ON u.product_id = p.product_id
    JOIN dim_seller s ON u.seller_id = s.seller_id
    WHERE u.is_new_seller = 0 AND u.units_sold > 0
    ORDER BY u.calc_date DESC, u.units_sold DESC
""", conn)
sales

## Daily Summary Per ASIN

In [ ]:
agg = pd.read_sql("""
    SELECT a.agg_date, p.asin, a.bsr_rank,
           ROUND(a.avg_price_weighted,2) AS avg_price,
           a.total_sellers, a.fba_sellers, a.fbm_sellers,
           a.total_units_sold
    FROM agg_product_daily a
    JOIN dim_product p ON a.product_id = p.product_id
    ORDER BY a.agg_date DESC
""", conn)
agg

## Inventory Snapshot — Run Any SQL

In [ ]:
# Edit this query freely
custom = pd.read_sql("""
    SELECT * FROM dim_product
""", conn)
custom